2024-08-05 23:59:38,732 - INFO - Running on 127.0.0.1:5003
2024-08-05 23:59:39,920 - INFO - Running on 127.0.0.1:5003
2024-08-05 23:59:41,242 - INFO - Rendering home page.
2024-08-05 23:59:53,899 - DEBUG - Received form data: {'request_num': '110329344', 'job_num': '114559784', 'machine': 'machine2', 'getdata': 'Get Data'}
2024-08-05 23:59:53,899 - DEBUG - Making API request to: https://huid.manakonline.in/MANAK/getxrfJobdetails?reqno=110329344&jobno=114559784 with data: {'username': 'vbhcxrf1', 'key': 'a4f8b0c36ed68294e497819f3fe6c6f69940b4efedb916c13cfa2ae722d4ee09'}
2024-08-05 23:59:54,092 - ERROR - Exception occurred while fetching data from server: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "d:\workspace\GitHub\DinoPal-Flask\.venv\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\workspace\GitHub\DinoPal-Flask\app.py", line 90, in get_data_from_server
    if res.json()[0] != {'Error': 'No data found !! Please Check Your Job no and Req No '}:
       ^^^^^^^^^^
  File "d:\workspace\GitHub\DinoPal-Flask\.venv\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-08-05 23:59:54,095 - INFO - Data fetched for request_num 110329344 and job_num 114559784.
2024-08-05 23:59:54,095 - ERROR - Error in getting data from server: Expecting value: line 1 column 1 (char 0)
2024-08-06 00:01:48,135 - INFO - Running on 127.0.0.1:5003
2024-08-06 00:01:49,429 - INFO - Running on 127.0.0.1:5003
2024-08-06 00:01:50,695 - INFO - Rendering home page.
2024-08-06 00:02:00,900 - DEBUG - Received form data: {'request_num': '110329344', 'job_num': '114559784', 'machine': 'machine2', 'getdata': 'Get Data'}
2024-08-06 00:02:00,900 - DEBUG - Making API request to: https://huid.manakonline.in/MANAK/getxrfJobdetails?reqno=110329344&jobno=114559784 with data: {'username': 'vbhcxrf1', 'key': 'a4f8b0c36ed68294e497819f3fe6c6f69940b4efedb916c13cfa2ae722d4ee09'}
2024-08-06 00:02:01,062 - DEBUG - Raw response content: 
2024-08-06 00:02:01,063 - ERROR - Exception occurred while fetching data from server: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "d:\workspace\GitHub\DinoPal-Flask\.venv\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\workspace\GitHub\DinoPal-Flask\app.py", line 92, in get_data_from_server
    if res.json()[0] != {'Error': 'No data found !! Please Check Your Job no and Req No '}:
       ^^^^^^^^^^
  File "d:\workspace\GitHub\DinoPal-Flask\.venv\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-08-06 00:02:01,068 - INFO - Data fetched for request_num 110329344 and job_num 114559784.
2024-08-06 00:02:01,069 - ERROR - Error in getting data from server: Expecting value: line 1 column 1 (char 0)
2024-08-06 00:03:15,411 - INFO - Running on 127.0.0.1:5003
2024-08-06 00:03:16,697 - INFO - Running on 127.0.0.1:5003
2024-08-06 00:03:18,488 - DEBUG - Received form data: {'request_num': '110329344', 'job_num': '114559784', 'machine': 'machine2', 'getdata': 'Get Data'}
2024-08-06 00:03:18,488 - DEBUG - Making API request to: https://huid.manakonline.in/MANAK/getxrfJobdetails?reqno=110329344&jobno=114559784 with data: {'username': 'vbhcxrf1', 'key': 'a4f8b0c36ed68294e497819f3fe6c6f69940b4efedb916c13cfa2ae722d4ee09'}
2024-08-06 00:03:18,685 - DEBUG - Raw response content: 
2024-08-06 00:03:18,686 - ERROR - Exception occurred while fetching data from server: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "d:\workspace\GitHub\DinoPal-Flask\.venv\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\workspace\GitHub\DinoPal-Flask\app.py", line 93, in get_data_from_server
    if res.json()[0] != {'Error': 'No data found !! Please Check Your Job no and Req No '}:
       ^^^^^^^^^^
  File "d:\workspace\GitHub\DinoPal-Flask\.venv\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-08-06 00:03:18,691 - INFO - Data fetched for request_num 110329344 and job_num 114559784.
2024-08-06 00:03:18,691 - ERROR - Error in getting data from server: Expecting value: line 1 column 1 (char 0)
